<?php

declare(strict_types=1);

namespace nameless\CodeGenerator\Support;

use nameless\CodeGenerator\ValueObjects\FieldDefinition;
use nameless\CodeGenerator\ValueObjects\RelationshipDefinition;
use nameless\CodeGenerator\ValueObjects\EntityDefinition;
use nameless\CodeGenerator\Exceptions\CodeGeneratorException;
use Illuminate\Support\Collection;
use Illuminate\Support\Str;

class JsonParser
{
    /**
     * Parse JSON data and convert to EntityDefinition objects.
     *
     * @return Collection<int, EntityDefinition>
     */
    public function parseJsonToEntities(string $jsonData): Collection
    {
        $data = json_decode($jsonData, true);
        
        if (json_last_error() !== JSON_ERROR_NONE) {
            throw CodeGeneratorException::invalidJsonData(json_last_error_msg());
        }

        // Handle different JSON formats
        $classes = $this->normalizeJsonData($data);

        return collect($classes)
            ->map(function (array $classData) {
                return $this->createEntityDefinition($classData);
            })
            ->filter(function (EntityDefinition $entity) {
                // Skip entities with no fields (e.g., all void types filtered out)
                return $entity->fields->isNotEmpty();
            })
            ->values();
    }

    /**
     * Normalize JSON data to consistent format.
     *
     * @param array<int|string, mixed> $data
     * @return array<int, array<string, mixed>>
     */
    private function normalizeJsonData(array $data): array
    {
        // Handle wrapped data format
        if (isset($data['data']) && is_array($data['data'])) {
            /** @var array<int, array<string, mixed>> */
            return [$data];
        }

        // Handle array of entities
        if (!isset($data['name'])) {
            /** @var array<int, array<string, mixed>> */
            return array_values($data);
        }

        // Handle single entity
        /** @var array<int, array<string, mixed>> */
        return [$data];
    }

    /**
     * Create EntityDefinition from array data.
     *
     * @param array<string, mixed> $classData
     */
    private function createEntityDefinition(array $classData): EntityDefinition
    {
        $class = isset($classData['data']) ? $classData['data'] : $classData;
        
        $name = ucfirst($class['name']);
        $parent = isset($class['parent']) ? ucfirst($class['parent']) : null;
        
        $fields = $this->parseFields($class['attributes'] ?? []);
        $relationships = $this->parseRelationships($class);
        
        return new EntityDefinition(
            name: $name,
            fields: $fields,
            relationships: $relationships,
            parent: $parent
        );
    }

    /**
     * Parse fields from attributes array.
     * Filters out id fields, void types, and duplicates.
     *
     * @param array<int, array<string, mixed>> $attributes
     * @return Collection<int, FieldDefinition>
     */
    private function parseFields(array $attributes): Collection
    {
        $seenNames = [];

        return collect($attributes)->filter(function (array $attribute) use (&$seenNames) {
            $name = $attribute['name'];
            $type = strtolower($attribute['_type'] ?? 'string');

            // Skip id field (auto-generated by Laravel)
            if ($name === 'id') {
                return false;
            }

            // Skip void types (usually UML diagram artifacts)
            if ($type === 'void') {
                return false;
            }

            // Skip duplicate field names
            if (in_array($name, $seenNames, true)) {
                return false;
            }

            $seenNames[] = $name;
            return true;
        })->map(function (array $attribute) {
            return new FieldDefinition(
                name: $attribute['name'],
                type: $this->normalizeType($attribute['_type'] ?? 'string')
            );
        })->values();
    }

    /**
     * Parse relationships from class data.
     * Supports explicit relationships, compositions, and aggregations.
     *
     * @param array<string, mixed> $classData
     * @return Collection<int, RelationshipDefinition>
     */
    private function parseRelationships(array $classData): Collection
    {
        $relationships = collect();

        // Explicit relationship keys
        $relationTypes = [
            'oneToOneRelationships' => 'oneToOne',
            'oneToManyRelationships' => 'oneToMany',
            'manyToOneRelationships' => 'manyToOne',
            'manyToManyRelationships' => 'manyToMany',
        ];

        foreach ($relationTypes as $key => $type) {
            if (isset($classData[$key]) && is_array($classData[$key])) {
                foreach ($classData[$key] as $relation) {
                    $relationships->push(new RelationshipDefinition(
                        type: $type,
                        relatedModel: ucfirst($relation['comodel'] ?? $relation['relatedModel'] ?? 'Unknown'),
                        role: $relation['role'] ?? Str::camel($relation['comodel'] ?? $relation['relatedModel'] ?? 'unknown')
                    ));
                }
            }
        }

        // UML compositions → oneToMany (strong ownership)
        if (isset($classData['compositions']) && is_array($classData['compositions'])) {
            foreach ($classData['compositions'] as $comp) {
                $relatedModel = ucfirst($comp['_type'] ?? $comp['comodel'] ?? '');
                if (empty($relatedModel)) {
                    continue;
                }
                $role = $comp['name'] ?? Str::camel($relatedModel);
                $relationships->push(new RelationshipDefinition(
                    type: 'oneToMany',
                    relatedModel: $relatedModel,
                    role: $role
                ));
            }
        }

        // UML aggregations → oneToMany (weak ownership)
        if (isset($classData['aggregations']) && is_array($classData['aggregations'])) {
            foreach ($classData['aggregations'] as $agg) {
                $relatedModel = ucfirst($agg['_type'] ?? $agg['comodel'] ?? '');
                if (empty($relatedModel)) {
                    continue;
                }
                $role = $agg['name'] ?? Str::camel($relatedModel);
                $relationships->push(new RelationshipDefinition(
                    type: 'oneToMany',
                    relatedModel: $relatedModel,
                    role: $role
                ));
            }
        }

        return $relationships;
    }

    /**
     * Normalize type names from various sources (UML, Java, custom) to Laravel types.
     */
    private function normalizeType(string $type): string
    {
        return match (strtolower($type)) {
            // Integer variants
            'integer', 'long', 'tinyint', 'smallint', 'mediumint', 'short', 'byte' => 'int',
            'bigint', 'biginteger' => 'bigint',

            // String variants
            'str', 'string', 'varchar', 'char', 'enum', 'set',
            'java.time.offsetdatetime', 'java.time.localdate' => 'string',

            // Text
            'text', 'longtext', 'mediumtext', 'tinytext', 'clob' => 'text',

            // Boolean
            'boolean', 'bool' => 'bool',

            // Float/Decimal variants
            'float', 'double', 'real', 'number' => 'float',
            'decimal', 'java.math.bigdecimal', 'money' => 'decimal',

            // Date/Time
            'date', 'localdate' => 'date',
            'datetime', 'timestamp', 'localdatetime' => 'datetime',
            'time', 'localtime' => 'time',

            // JSON / Array
            'json', 'jsonb', 'array', 'list', 'map', 'object',
            'java.util.map', 'java.util.list' => 'json',

            // UUID
            'uuid' => 'uuid',

            // Catch-all: types like list_uuid, list_string, etc.
            default => str_starts_with(strtolower($type), 'list_') ? 'json' : 'string',
        };
    }
}
