<?php

declare(strict_types=1);

namespace nameless\CodeGenerator\Support;

use Illuminate\Support\Collection;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Str;
use nameless\CodeGenerator\Exceptions\CodeGeneratorException;
use nameless\CodeGenerator\ValueObjects\EntityDefinition;
use nameless\CodeGenerator\ValueObjects\FieldDefinition;
use nameless\CodeGenerator\ValueObjects\RelationshipDefinition;

/**
 * Parses Mermaid `classDiagram` and `erDiagram` definitions into
 * EntityDefinition objects, so an API can be generated by pasting the
 * diagram of your data model:
 *
 * ```mermaid
 * erDiagram
 *     USER ||--o{ POST : writes
 *     POST {
 *         string title
 *         text content
 *     }
 * ```
 *
 * Conventions:
 * - class members with parentheses (methods) are ignored
 * - `id`, timestamps and PK columns are ignored; `deleted_at` enables soft deletes
 * - FK columns (`xxx_id` or marked FK) are ignored: foreign keys are derived
 *   from the diagram relationships instead
 * - relationship labels become the Eloquent method name when present
 */
class MermaidParser
{
    /** @var array<int, string> */
    private array $warnings = [];

    /** @var array<string, array{fields: array<string, FieldDefinition>, relations: array<int, RelationshipDefinition>, soft_deletes: bool, parent: ?string, declared: bool}> */
    private array $entities = [];

    private const SKIP_COLUMNS = ['id', 'created_at', 'updated_at'];

    /**
     * @param  array<string, mixed>  $extraOptions
     * @return Collection<int, EntityDefinition>
     */
    public function parseFile(string $path, array $extraOptions = []): Collection
    {
        if (! File::exists($path)) {
            throw CodeGeneratorException::fileNotFound($path);
        }

        return $this->parse(File::get($path), $extraOptions, $path);
    }

    /**
     * @param  array<string, mixed>  $extraOptions
     * @return Collection<int, EntityDefinition>
     */
    public function parse(string $diagram, array $extraOptions = [], string $source = 'diagram'): Collection
    {
        $this->warnings = [];
        $this->entities = [];

        $lines = $this->cleanLines($diagram);
        if ($lines === []) {
            throw CodeGeneratorException::invalidDiagram($source, 'the diagram is empty');
        }

        $header = array_shift($lines);

        if (str_starts_with($header, 'classDiagram')) {
            $this->parseClassDiagram($lines);
        } elseif (str_starts_with($header, 'erDiagram')) {
            $this->parseErDiagram($lines);
        } else {
            throw CodeGeneratorException::invalidDiagram($source, "expected 'classDiagram' or 'erDiagram', found '{$header}'");
        }

        return $this->buildDefinitions($extraOptions, $source);
    }

    /**
     * Warnings collected during the last parse (dropped entities/relations).
     *
     * @return array<int, string>
     */
    public function getWarnings(): array
    {
        return $this->warnings;
    }

    // ─── classDiagram ───────────────────────────────────────────────────

    /**
     * @param  array<int, string>  $lines
     */
    private function parseClassDiagram(array $lines): void
    {
        $currentClass = null;

        foreach ($lines as $line) {
            // class Foo {  /  class Foo
            if (preg_match('/^class\s+([A-Za-z_][\w]*)\s*(\{)?\s*$/', $line, $m)) {
                $name = $this->normalizeClassName($m[1]);
                $this->ensureEntity($name, declared: true);
                $currentClass = isset($m[2]) ? $name : null;

                continue;
            }

            if ($currentClass !== null) {
                if (str_starts_with($line, '}')) {
                    $currentClass = null;

                    continue;
                }
                $this->parseClassMember($currentClass, $line);

                continue;
            }

            // Foo : +String title   (single-line member)
            if (preg_match('/^([A-Za-z_][\w]*)\s*:\s*(.+)$/', $line, $m) && ! str_contains($m[2], '--')) {
                $name = $this->normalizeClassName($m[1]);
                $this->ensureEntity($name, declared: true);
                $this->parseClassMember($name, $m[2]);

                continue;
            }

            $this->parseClassRelationship($line);
        }
    }

    private function parseClassMember(string $className, string $line): void
    {
        // Skip annotations and methods
        if (str_starts_with($line, '<<') || str_contains($line, '(')) {
            return;
        }

        // Strip visibility marker and generics: +List~String~ tags
        $member = ltrim($line, '+-#~ ');
        $member = trim($member);
        if ($member === '') {
            return;
        }

        $tokens = preg_split('/\s+/', $member) ?: [];

        if (count($tokens) >= 2) {
            $type = preg_replace('/~.*~/', '', $tokens[0]) ?? $tokens[0];
            $fieldName = $tokens[1];
        } else {
            $type = 'string';
            $fieldName = $tokens[0];
        }

        $fieldName = trim($fieldName, ',;');
        if (! preg_match('/^[a-zA-Z_][a-zA-Z0-9_]*$/', $fieldName)) {
            return;
        }

        $this->addField($className, $fieldName, TypeNormalizer::fromSchemaType($type));
    }

    private function parseClassRelationship(string $line): void
    {
        $arrows = '<\|--|--\|>|\.\.\|>|<\|\.\.|\*--|--\*|o--|--o|-->|<--|\.\.>|<\.\.|--|\.\.';
        if (! preg_match(
            '/^([A-Za-z_][\w]*)\s*(?:"([^"]*)"\s*)?('.$arrows.')\s*(?:"([^"]*)"\s*)?([A-Za-z_][\w]*)\s*(?::\s*(.*))?$/',
            $line,
            $m
        )) {
            return;
        }

        $left = $this->normalizeClassName($m[1]);
        $cardLeft = $m[2];
        $arrow = $m[3];
        $cardRight = $m[4];
        $right = $this->normalizeClassName($m[5]);
        $label = trim($m[6] ?? '');

        // Dependencies / realizations are not data relationships
        if (in_array($arrow, ['..>', '<..', '..|>', '<|..', '..'], true)) {
            return;
        }

        // Inheritance: arrowhead points at the parent
        if ($arrow === '<|--') {
            $this->ensureEntity($right);
            $this->entities[$right]['parent'] = $left;
            $this->ensureEntity($left);

            return;
        }
        if ($arrow === '--|>') {
            $this->ensureEntity($left);
            $this->entities[$left]['parent'] = $right;
            $this->ensureEntity($right);

            return;
        }

        // Normalize direction so the "owning" side is always on the left
        if ($arrow === '<--') {
            [$left, $right] = [$right, $left];
            [$cardLeft, $cardRight] = [$cardRight, $cardLeft];
            $arrow = '-->';
        } elseif ($arrow === '--*' || $arrow === '--o') {
            [$left, $right] = [$right, $left];
            [$cardLeft, $cardRight] = [$cardRight, $cardLeft];
            $arrow = $arrow === '--*' ? '*--' : 'o--';
        }

        $this->ensureEntity($left);
        $this->ensureEntity($right);

        // Composition / aggregation without explicit cardinality: whole has many parts
        if (in_array($arrow, ['*--', 'o--'], true) && $cardLeft === '' && $cardRight === '') {
            $this->addOneToMany($left, $right, $label);

            return;
        }

        $leftMany = $this->isMany($cardLeft);
        $rightMany = $this->isMany($cardRight);

        if ($cardLeft === '' && $cardRight === '' && $arrow === '-->') {
            // Plain association: the declaring class references one target
            $this->addManyToOne($left, $right, $label);

            return;
        }

        match (true) {
            $leftMany && $rightMany => $this->addManyToMany($left, $right, $label),
            $rightMany => $this->addOneToMany($left, $right, $label),
            $leftMany => $this->addManyToOne($left, $right, $label),
            default => $this->addOneToOne($left, $right, $label),
        };
    }

    // ─── erDiagram ──────────────────────────────────────────────────────

    /**
     * @param  array<int, string>  $lines
     */
    private function parseErDiagram(array $lines): void
    {
        $currentEntity = null;

        foreach ($lines as $line) {
            // ENTITY {
            if (preg_match('/^([A-Za-z_][\w-]*)\s*\{\s*$/', $line, $m)) {
                $currentEntity = $this->normalizeErName($m[1]);
                $this->ensureEntity($currentEntity, declared: true);

                continue;
            }

            if ($currentEntity !== null) {
                if (str_starts_with($line, '}')) {
                    $currentEntity = null;

                    continue;
                }
                $this->parseErAttribute($currentEntity, $line);

                continue;
            }

            // USER ||--o{ POST : writes
            if (preg_match(
                '/^([A-Za-z_][\w-]*)\s+(\}o|\}\||\|\||\|o|o\|)(--|\.\.)(o\{|\|\{|\|\||o\||\|o)\s+([A-Za-z_][\w-]*)\s*(?::\s*(.+))?$/',
                $line,
                $m
            )) {
                $left = $this->normalizeErName($m[1]);
                $right = $this->normalizeErName($m[5]);
                $leftMany = str_contains($m[2], '}');
                $rightMany = str_contains($m[4], '{');

                $this->ensureEntity($left);
                $this->ensureEntity($right);

                match (true) {
                    $leftMany && $rightMany => $this->addManyToMany($left, $right, ''),
                    $rightMany => $this->addOneToMany($left, $right, ''),
                    $leftMany => $this->addManyToOne($left, $right, ''),
                    // one-to-one: FK on the right-hand entity (Laravel convention)
                    default => $this->addOneToOne($right, $left, ''),
                };
            }
        }
    }

    private function parseErAttribute(string $entityName, string $line): void
    {
        // <type> <name> [PK|FK|UK, ...] ["comment"]
        if (! preg_match('/^([\w~()]+)\s+([A-Za-z_][\w]*)\s*(.*)$/', $line, $m)) {
            return;
        }

        $type = $m[1];
        $fieldName = $m[2];
        $modifiers = strtoupper($m[3]);

        if (str_contains($modifiers, 'PK') || str_contains($modifiers, 'FK') || str_ends_with($fieldName, '_id')) {
            return;
        }

        $this->addField($entityName, $fieldName, TypeNormalizer::fromSchemaType($type), unique: str_contains($modifiers, 'UK'));
    }

    // ─── Shared assembly ────────────────────────────────────────────────

    /**
     * @return array{fields: array<string, FieldDefinition>, relations: array<int, RelationshipDefinition>, soft_deletes: bool, parent: ?string, declared: bool}
     */
    private function ensureEntity(string $name, bool $declared = false): array
    {
        if (! isset($this->entities[$name])) {
            $this->entities[$name] = [
                'fields' => [],
                'relations' => [],
                'soft_deletes' => false,
                'parent' => null,
                'declared' => $declared,
            ];
        } elseif ($declared) {
            $this->entities[$name]['declared'] = true;
        }

        return $this->entities[$name];
    }

    private function addField(string $entityName, string $fieldName, string $type, bool $unique = false): void
    {
        if ($fieldName === 'deleted_at') {
            $this->entities[$entityName]['soft_deletes'] = true;

            return;
        }
        if (in_array($fieldName, self::SKIP_COLUMNS, true) || isset($this->entities[$entityName]['fields'][$fieldName])) {
            return;
        }

        $this->entities[$entityName]['fields'][$fieldName] = new FieldDefinition(
            name: $fieldName,
            type: $type,
            unique: $unique
        );
    }

    private function addOneToMany(string $one, string $many, string $label): void
    {
        $this->addRelation($one, 'oneToMany', $many, $label !== '' ? $label : Str::camel(Str::plural($many)));
        $this->addRelation($many, 'manyToOne', $one, Str::camel($one));
    }

    private function addManyToOne(string $many, string $one, string $label): void
    {
        $this->addRelation($many, 'manyToOne', $one, $label !== '' ? $label : Str::camel($one));
        $this->addRelation($one, 'oneToMany', $many, Str::camel(Str::plural($many)));
    }

    private function addManyToMany(string $a, string $b, string $label): void
    {
        $this->addRelation($a, 'manyToMany', $b, $label !== '' ? $label : Str::camel(Str::plural($b)));
        $this->addRelation($b, 'manyToMany', $a, Str::camel(Str::plural($a)));
    }

    private function addOneToOne(string $owner, string $target, string $label): void
    {
        $this->addRelation($owner, 'oneToOne', $target, $label !== '' ? $label : Str::camel($target));
    }

    private function addRelation(string $entityName, string $type, string $relatedModel, string $role): void
    {
        $role = Str::camel(preg_replace('/[^a-zA-Z0-9]+/', '_', trim($role)) ?? $role);
        if ($role === '') {
            $role = Str::camel($relatedModel);
        }

        foreach ($this->entities[$entityName]['relations'] as $existing) {
            if ($existing->role === $role) {
                return;
            }
        }

        $this->entities[$entityName]['relations'][] = new RelationshipDefinition(
            type: $type,
            relatedModel: $relatedModel,
            role: $role
        );
    }

    /**
     * @param  array<string, mixed>  $extraOptions
     * @return Collection<int, EntityDefinition>
     */
    private function buildDefinitions(array $extraOptions, string $source): Collection
    {
        $emitted = [];
        foreach ($this->entities as $name => $entity) {
            if ($entity['fields'] === []) {
                $this->warnings[] = "Entity '{$name}' was skipped: it appears in relationships but declares no attributes.";

                continue;
            }
            $emitted[$name] = $entity;
        }

        if ($emitted === []) {
            throw CodeGeneratorException::invalidDiagram($source, 'no entity with attributes found');
        }

        $definitions = collect();
        foreach ($emitted as $name => $entity) {
            $relations = [];
            foreach ($entity['relations'] as $relation) {
                if (! isset($emitted[$relation->relatedModel])) {
                    $this->warnings[] = "Relation '{$name}.{$relation->role}' was dropped: '{$relation->relatedModel}' is not generated.";

                    continue;
                }
                $relations[] = $relation;
            }

            $parent = $entity['parent'];
            if ($parent !== null && ! isset($emitted[$parent])) {
                $this->warnings[] = "Parent '{$parent}' of '{$name}' is not generated; inheritance ignored.";
                $parent = null;
            }

            $definitions->push(new EntityDefinition(
                name: $name,
                fields: collect(array_values($entity['fields'])),
                relationships: collect($relations),
                parent: $parent,
                options: array_merge($extraOptions, ['soft_deletes' => $entity['soft_deletes']])
            ));
        }

        return EntitySorter::sortByDependencies(
            RelationshipSynthesizer::resolveRelatedKeys(RelationshipSynthesizer::addInverses($definitions))
        );
    }

    // ─── Helpers ────────────────────────────────────────────────────────

    /**
     * @return array<int, string>
     */
    private function cleanLines(string $diagram): array
    {
        $lines = [];
        foreach (preg_split('/\r?\n/', $diagram) ?: [] as $line) {
            $line = trim($line);
            // Skip blanks, markdown fences, mermaid comments and directives
            if ($line === '' || str_starts_with($line, '```') || str_starts_with($line, '%%') || str_starts_with($line, 'direction ')) {
                continue;
            }
            $lines[] = $line;
        }

        return $lines;
    }

    private function normalizeClassName(string $name): string
    {
        return ucfirst($name);
    }

    private function normalizeErName(string $name): string
    {
        return Str::studly(Str::singular(strtolower($name)));
    }

    private function isMany(string $cardinality): bool
    {
        $c = strtolower(trim($cardinality));

        return str_contains($c, '*') || str_contains($c, 'many') || str_ends_with($c, 'n');
    }
}
